#!/bin/sh

SCRIPTNAME="$(basename $0)"
VERSION="0.47.1"

# Helper functions for guards
error(){
  error_code=$1
  echo "ERROR: $2" >&2
  echo "($SCRIPTNAME wrapper version: $VERSION, error code: $error_code )" &>2
  exit $1
}
check_cmd_in_path(){
  cmd=$1
  which $cmd > /dev/null 2>&1 || error 1 "$cmd not found!"
}

# Guards (checks for dependencies)
check_cmd_in_path docker

if [ -z "$CODE_DIR" ]; then
  export CODE_DIR=$PWD
fi

exec docker run \
  --interactive \
  --tty \
  --rm \
  --volume "$CODE_DIR":/app \
  --workdir /app \
  "nicklinnell/rubocop:$VERSION" "$@"
